# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iQRLbDcIOgnIwqu0FfOxQP7vmDvSbgDv
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import pandas as pd

df=pd.read_csv("Titanic-Dataset.csv")
df

current_pallete1=sns.color_palette()
sns.palplot(current_pallete1)
plt.show

current_pallete2=sns.color_palette()
sns.palplot(sns.color_palette("Reds"))
plt.show

current_pallete3=sns.color_palette()
sns.palplot(sns.color_palette("BrBG",10))
plt.show

current_pallete3=sns.color_palette()
sns.palplot(sns.color_palette("colorblind"))
plt.show

df.shape

df.head()

sns.histplot(df['Parch'],kde=False)
plt.show()

sns.distplot(df['Age'],hist=False)
plt.show()

plt.figure(figsize=(8,8))
sns.distplot(df['Age'])
plt.show()

sns.relplot(x="Age",y="Fare",col="Pclass",hue="Sex",style="Sex",kind="line",data=df)
plt.show()

plt.figure(figsize=(8,8))
sns.scatterplot(x="Age",y="Fare",hue="Sex",data=df)
plt.show()

plt.figure(figsize=(8,8))
sns.lineplot(x="Age",y="Fare",hue="Sex", style="Sex",data=df)
plt.show()

plt.figure(figsize=(8,8))
sns.barplot(x="Sex",y="Survived",hue="Pclass",data=df)
plt.show()

plt.figure(figsize=(8,8))
sns.stripplot(x="Sex",y="Age",hue="Sex",data=df)
plt.show()

plt.figure(figsize=(8,8))
sns.swarmplot(x="Sex",y="Age",hue="Sex",data=df)
plt.show()

plt.figure(figsize=(8,8))
sns.boxplot(x="Survived",y="Age",data=df)
plt.show()

sns.violinplot(x="Survived",y="Age",hue="Sex",data=df)
plt.show()

sns.countplot(x="Survived",data=df,palette="Blues")
plt.show()

plt.subplots(figsize=(8,8))
sns.pointplot(x="Sex",y="Survived",hue="Pclass",data=df)
plt.show()

sns.lmplot(x="Age",y="Fare",data=df)
plt.show()

plt.subplots(figsize=(10,10))
sns.regplot(x="Age",y="Fare",data=df)
plt.show()

plt.subplots(figsize=(10,10))
sns.regplot(x="Fare",y="Fare",data=df)
plt.show()

numeric_df = df.select_dtypes(include=['number'])

# Compute the correlation matrix
corr_matrix = numeric_df.corr()

# Plot the heatmap
plt.figure(figsize=(10, 10))
sns.heatmap(corr_matrix, cmap="YlGnBu", annot=True, fmt=".2f")
plt.show()

g=sns.FacetGrid(df,col="Survived",row='Pclass')

g.map(plt.hist,'Age')
g.add_legend()
plt.show()